services:
  eduard-simulation:
    image: eduartrobotik/eduart-simulation:0.4.0
    container_name: eduart-simulation-0.4.0
    user: user
    privileged: true
    ipc: host
    pid: host
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
      - EDU_ROBOT_NAMESPACE=${EDU_ROBOT_NAMESPACE:-eduard}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
#            - CYCLONEDDS_URI=/home/user/ros/launch_content/cyclone_profile.xml         
    network_mode: "host" # should be ignored on macOS
    command: tail -F anything # keep container running without doing anything
    volumes:
      # - './launch_content:/home/user/ros/launch_content:r'
      - '/dev:/dev'
      - '/tmp/.X11-unix:/tmp/.X11-unix:rw'
    devices:
      - '/dev:/dev'
